import type { EditDocumentV2 } from "@/api/control-plane";

/** One bounded version 2 document shared by the timeline and issues tests. */
export function timelineDocument(): EditDocumentV2 {
  return {
    schema_version: 2,
    document_id: "document_002",
    project_id: "project_001",
    revision: 4,
    canvas: { width: 1080, height: 1920, fps: 30, duration_in_frames: 300 },
    template: { template_id: "vertical_text_story", version: 1 },
    scenes: [
      {
        scene_id: "scene_001",
        role: "source",
        start_frame: 0,
        duration_in_frames: 300,
        clip_ids: ["clip_main"],
      },
    ],
    asset_refs: [
      {
        asset_id: "asset_video",
        project_id: "project_001",
        kind: "video",
        has_audio: true,
        validation_state: "ready",
      },
      {
        asset_id: "asset_music",
        project_id: "project_001",
        kind: "audio",
        has_audio: true,
        validation_state: "ready",
      },
    ],
    tracks: [
      {
        track_id: "track_main",
        kind: "main_video",
        label: "Main video",
        order: 0,
        hidden: false,
        muted: false,
        locked: false,
        clip_ids: ["clip_main"],
      },
      {
        track_id: "track_broll",
        kind: "b_roll",
        label: "B-roll",
        order: 1,
        hidden: false,
        muted: false,
        locked: false,
        clip_ids: ["clip_locked"],
      },
      {
        track_id: "track_music",
        kind: "music",
        label: "Music",
        order: 2,
        hidden: false,
        muted: false,
        locked: false,
        clip_ids: ["clip_music"],
      },
      {
        track_id: "track_captions",
        kind: "caption",
        label: "Captions",
        order: 3,
        hidden: true,
        muted: false,
        locked: true,
        clip_ids: [],
      },
    ],
    clips: [
      {
        kind: "video",
        clip_id: "clip_main",
        track_id: "track_main",
        asset_id: "asset_video",
        from_frame: 0,
        duration_in_frames: 120,
        source_from_frame: 0,
        ownership: "ai_managed",
        hidden: false,
        locked: false,
        fit: "cover",
      },
      {
        kind: "video",
        clip_id: "clip_locked",
        track_id: "track_broll",
        asset_id: "asset_video",
        from_frame: 150,
        duration_in_frames: 50,
        source_from_frame: 0,
        ownership: "ai_managed",
        hidden: false,
        locked: true,
        fit: "cover",
      },
      {
        kind: "audio",
        clip_id: "clip_music",
        track_id: "track_music",
        asset_id: "asset_music",
        from_frame: 150,
        duration_in_frames: 90,
        source_from_frame: 0,
        ownership: "user_edited",
        hidden: false,
        locked: false,
        volume: 0.8,
        fade_in_frames: 0,
        fade_out_frames: 0,
      },
    ],
  };
}
