use serde::{Deserialize, Serialize};

/// Reaction script generated by the LLM for a single viral moment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReactionScript {
    /// The reaction text to be synthesized by TTS.
    pub script: String,
    /// Tone of the reaction: "shocked" | "informative" | "amused" | "concerned" | "amazed"
    pub tone: String,
    /// Estimated speaking duration in seconds (LLM hint, overridden by actual TTS duration).
    pub duration_estimate_secs: f64,
    /// Suggested avatar facial expression for D-ID/HeyGen.
    #[serde(default)]
    pub suggested_avatar_expression: String,
}

impl ReactionScript {
    /// Return true when the script has at least a few words of content.
    pub fn is_valid(&self) -> bool {
        self.script.split_whitespace().count() >= 5
    }
}

/// Tone guide for a given viral_type — directs LLM prompt construction.
pub fn tone_guide_for(viral_type: &str) -> (&'static str, &'static str) {
    match viral_type {
        "controversy"        => ("shocked/concerned",  "Tunggu, ini beneran?! Jadi..."),
        "educational_shock"  => ("amazed/informative", "Nah ini yang banyak orang gak tau..."),
        "transformation"     => ("amazed/inspired",    "Gila ya, bayangin dari..."),
        "actionable"         => ("enthusiastic",       "Oke ini penting banget, dengerin..."),
        "relatable"          => ("amused",             "Hahaha ini gue banget, soalnya..."),
        "blueprint"          => ("informative",        "Jadi step-nya tuh gini..."),
        "inspiration"        => ("admiring",           "Ini keren banget, karena..."),
        "storytelling"       => ("engaged",            "Seriusan, dengerin cerita ini..."),
        _                    => ("natural",            "Jadi,"),
    }
}
